# Writes apps/mobile/.env with LAN API URL for physical device testing.
$ErrorActionPreference = "Stop"

$scriptsDir = $PSScriptRoot
$root = Split-Path $scriptsDir -Parent
$envPath = Join-Path $root "apps\mobile\.env"
$examplePath = Join-Path $root "apps\mobile\.env.example"

function Get-LanIp {
  $wlan = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
      $_.IPAddress -notlike "127.*" -and
      $_.IPAddress -notlike "169.254.*" -and
      $_.InterfaceAlias -match "WLAN|Wi-?Fi|Ethernet"
    } |
    Sort-Object { if ($_.InterfaceAlias -match "WLAN|Wi-?Fi") { 0 } else { 1 } }

  if ($wlan) {
    return ($wlan | Select-Object -First 1).IPAddress
  }

  return (
    Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
      Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |
      Select-Object -First 1
  ).IPAddress
}

$lanIp = Get-LanIp
if (-not $lanIp) {
  throw "Could not detect LAN IP. Set EXPO_PUBLIC_API_BASE_URL manually in apps/mobile/.env"
}

$existingKey = $null
if (Test-Path $envPath) {
  $existingKey = Select-String -Path $envPath -Pattern "^EXPO_PUBLIC_OPENAI_API_KEY=(.+)$" |
    ForEach-Object { $_.Matches[0].Groups[1].Value }
}

$apiLine = "EXPO_PUBLIC_API_BASE_URL=http://${lanIp}:8080"
$keyLine = if ($existingKey -and $existingKey -ne "sk-your-key-here") {
  "EXPO_PUBLIC_OPENAI_API_KEY=$existingKey"
} else {
  "EXPO_PUBLIC_OPENAI_API_KEY=sk-your-key-here"
}

@"
# Generated by scripts/setup-device-env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm")
# Restart Expo after changes (stop + pnpm start, or press r in terminal).
$keyLine
$apiLine
"@ | Set-Content -Path $envPath -Encoding utf8

Write-Host "Wrote $envPath"
Write-Host "  $apiLine"
if ($keyLine -match "sk-your-key") {
  Write-Host "  Replace EXPO_PUBLIC_OPENAI_API_KEY with your real key for auto transcription."
}
Write-Host ""
Write-Host "Next:"
Write-Host "  1. scripts\run-session-service.cmd"
Write-Host "  2. scripts\run-api-gateway.cmd"
Write-Host "  3. scripts\device-debug.ps1"
Write-Host "  4. scripts\run-mobile.cmd  (phone and PC on same Wi-Fi)"
